apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: nfd
  name: nfd-topology-updater
spec:
  selector:
    matchLabels:
      app: nfd-topology-updater
  template:
    metadata:
      labels:
        app: nfd-topology-updater
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      serviceAccount: nfd-topology-updater
      containers:
        - name: nfd-topology-updater
          image: gcr.io/k8s-staging-nfd/node-feature-discovery:master
          imagePullPolicy: Always
          command:
            - "nfd-topology-updater"
          args: []
