apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nfd-topology-gc
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nfd-topology-gc
subjects:
- kind: ServiceAccount
  name: nfd-topology-gc
  namespace: default
