apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

bases:
- ../../base/rbac
- ../../base/rbac-topologyupdater
- ../../base/rbac-topology-gc
- ../../base/nfd-crds
- ../../base/master
- ../../base/worker-daemonset
- ../../base/noderesourcetopologies-crd
- ../../base/topologyupdater-daemonset
- ../../base/topology-gc

resources:
- namespace.yaml

components:
- ../../components/worker-config
- ../../components/common
- ../../components/topology-updater
- ../../components/topology-updater-config
