apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - nfd-topology-updater.conf=nfd-topology-updater.conf.example
  name: nfd-topology-updater-conf
